//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementSystem.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string EmployeCode { get; set; }
        public string CNICNo { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string CellNo { get; set; }
        public int FK_Department { get; set; }
        public int FK_Designation { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
